import { FiSearch, FiShoppingBag, FiMessageCircle, FiPlus } from 'react-icons/fi'
import './OrderingGuide.css'
const faqs=[
 ['How do I check if a part fits my vehicle?','Start with your make, model, and year. Before ordering, contact us with the product details and any relevant vehicle information so we can confirm compatibility.'],
 ['How do I complete my order?','Add your parts to the cart and select Place order. Use WhatsApp or SMS in the confirmation popup to send your order reference and item details to our team.'],
 ['Where do you deliver, and how much does it cost?','Contact us with your delivery location and order reference. Our team will confirm whether delivery is available, the cost, and the estimated timing before you proceed.'],
 ['Which payment methods can I use?','Our team will confirm the available payment options when you follow up on your order. Online payment is not currently available on this website.'],
 ['Can I return or exchange a part?','Please confirm return and exchange terms with our team before purchasing. If you have an issue with an order, contact us with your reference number and details so we can advise you on the next steps.'],
]
export default function OrderingGuide(){return <section className="ordering-guide"><div className="container"><header><span className="eyebrow">FROM YOUR GARAGE TO YOUR NEXT MILE</span><h2>How to <em>order.</em></h2><p>A few simple steps. A real person to help along the way.</p></header><div className="ordering-steps">{[[FiSearch,'Find your fit','Choose your vehicle and explore the right collection.'],[FiShoppingBag,'Build your order','Add your parts, check quantities, and select Place order.'],[FiMessageCircle,'Let us take it from here','Send your order reference via WhatsApp or SMS to confirm availability, payment, and delivery.']].map(([Icon,title,copy],i)=><article key={title}><div><span>0{i+1}</span><Icon /></div><h3>{title}</h3><p>{copy}</p></article>)}</div><div className="ordering-faq"><div><span className="eyebrow">A LITTLE CLARITY GOES A LONG WAY</span><h2>Good questions.<br /><em>Clear answers.</em></h2><p>Need something more specific?</p><a href="#contact">Talk to our team <FiMessageCircle /></a></div><div className="ordering-answers">{faqs.map(([question,answer])=><details name="ordering-faq" key={question}><summary>{question}<FiPlus aria-hidden="true" /></summary><p>{answer}</p></details>)}</div></div></div></section>}
