import { useRef, useState } from 'react'
import { toast } from 'react-toastify'
import { FiPlus, FiX, FiEdit2, FiTrash2 } from 'react-icons/fi'
import { useCollections } from '../../store/collections'
import { useCatalog } from '../../store/catalog'
import { departmentTypes } from '../../lib/productModel'
import { compressProductImage } from '../../lib/compressProductImage'
import PartArt from '../../components/PartArt'
export default function Collections(){
 const {collections,saveCollection,deleteCollection}=useCollections()
 const products=useCatalog(state=>state.products)
 const dialog=useRef(null),confirm=useRef(null)
 const [draft,setDraft]=useState({name:'',description:'',type:'brake',image:''})
 const [original,setOriginal]=useState(null),[pending,setPending]=useState(null),[busy,setBusy]=useState(false)
 const used=original&&products.some(p=>p.category===original)
 function open(item){setOriginal(item?.name||null);setDraft(item||{name:'',description:'',type:'brake',image:''});dialog.current.showModal()}
 function save(e){e.preventDefault();try{saveCollection(draft,original);dialog.current.close();toast.success('Collection saved.')}catch(err){toast.error(err.message)}}
 async function upload(e){const file=e.target.files[0];e.target.value='';if(!file)return;setBusy(true);try{const image=await compressProductImage(file);setDraft(value=>({...value,image}))}catch(err){toast.error(err.message)}finally{setBusy(false)}}
 function remove(){try{if(products.some(p=>p.category===pending))throw new Error('Move products to another collection before deleting this collection.');deleteCollection(pending);confirm.current.close();toast.success('Collection deleted.')}catch(err){toast.error(err.message)}}
 return <><section className="adm-panel"><div className="adm-panel-title"><h2>Collections <small>({collections.length})</small></h2><button className="adm-primary" onClick={()=>open()}><FiPlus /> Add collection</button></div><div className="adm-table-scroll"><table><thead><tr><th>Collection</th><th>Introduction</th><th>Products</th><th>Actions</th></tr></thead><tbody>{collections.map(item=><tr key={item.name}><td><div className="adm-table-product">{item.image?<img src={item.image} alt="" />:<PartArt type={item.type} />}<strong>{item.name}</strong></div></td><td>{item.description||'No introduction'}</td><td>{products.filter(p=>p.category===item.name).length}</td><td><div className="adm-row-actions"><button className="adm-icon" aria-label={'Edit '+item.name} onClick={()=>open(item)}><FiEdit2 /></button><button className="adm-icon adm-danger" aria-label={'Delete '+item.name} onClick={()=>{setPending(item.name);confirm.current.showModal()}}><FiTrash2 /></button></div></td></tr>)}</tbody></table></div></section><dialog ref={dialog} className="adm-confirm" aria-labelledby="collection-title" onCancel={e=>{if(busy)e.preventDefault()}}><form onSubmit={save}><div className="adm-panel-title"><h2 id="collection-title">{original?'Edit':'Add'} collection</h2><button disabled={busy} className="adm-icon" type="button" onClick={()=>dialog.current.close()} aria-label="Close"><FiX /></button></div><fieldset disabled={busy}><label>Collection name<input required readOnly={!!used} maxLength={60} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} /></label>{used&&<p>Move products first to rename this collection.</p>}<label>Short introduction<input maxLength={140} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} /></label><label>Collection type<select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value})}>{Object.entries(departmentTypes).map(([label,value])=><option key={value} value={value}>{label}</option>)}</select></label>{draft.image&&<img className="adm-current-image" src={draft.image} alt="Current collection image" />}<label className="adm-image-change">{draft.image?'Change image':'Upload image'}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={upload} /></label>{draft.image&&<div className="adm-collection-preview"><button type="button" onClick={()=>setDraft({...draft,image:''})}>Remove image</button></div>}<button className="adm-primary" type="submit">{busy?'Compressing image...':'Save collection'}</button></fieldset></form></dialog><dialog ref={confirm} className="adm-confirm"><h2>Delete {pending}?</h2><p>This removes the collection from your store.</p><button onClick={()=>confirm.current.close()}>Cancel</button><button className="adm-delete" onClick={remove}>Delete collection</button></dialog></>
}
