import { vehicleYearLabel } from '../../lib/vehicleYearLabel'
import { useRef, useState } from 'react'
import { toast } from 'react-toastify'
import { FiTrash2, FiSearch } from 'react-icons/fi'
import { useOrders } from '../../store/orders'
import { money } from '../../data/products'
export default function Orders(){
 const {orders,deleteOrder,busy,loading,updateStatus}=useOrders()
 const dialog=useRef(null),[pending,setPending]=useState(null)
 const [query,setQuery]=useState('')
 const filtered=orders.filter(order=>order.id.toLowerCase().includes(query.trim().toLowerCase()))
 return <section className="adm-panel"><div className="adm-panel-title"><h2>Orders</h2><span>{filtered.length} of {orders.length} orders</span></div><div className="adm-toolbar adm-order-filters"><label className="adm-search"><FiSearch /><input aria-label="Search order reference" placeholder="Search order reference..." value={query} onChange={e=>setQuery(e.target.value)} /></label></div><div className="adm-table-scroll"><table className="adm-orders-table"><thead><tr><th>Reference / Date</th><th>Products & quantities</th><th>Total items</th><th>Order total</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map(order=><tr key={order.id}><td><strong>{order.id}</strong><small>{new Date(order.createdAt).toLocaleString()}</small></td><td><table className="adm-order-lines" aria-label={'Items in '+order.id}><thead><tr><th>Product / Vehicle</th><th>Qty</th><th>Unit price</th><th>Subtotal</th></tr></thead><tbody>{order.items.map((item,index)=><tr key={index}><td>{item.name}<small>{item.vehicle} {vehicleYearLabel(item.years)||'(year not recorded)'}</small></td><td>{item.quantity}</td><td>{money(item.price)}</td><td>{money(item.price*item.quantity)}</td></tr>)}</tbody></table></td><td>{order.items.reduce((sum,item)=>sum+item.quantity,0)}</td><td><strong>{money(order.total)}</strong></td><td><select aria-label={'Status for '+order.id} disabled={busy} value={order.status} onChange={async e=>{try{await updateStatus(order.id,e.target.value);toast.success('Order status updated.')}catch(err){toast.error(err.message)}}}>{['pending','confirmed','shipped','completed','cancelled'].map(status=><option key={status}>{status}</option>)}</select></td><td><button disabled={busy} className="adm-icon adm-danger" aria-label={'Delete order '+order.id} onClick={()=>{setPending(order.id);dialog.current.showModal()}}><FiTrash2 /></button></td></tr>)}</tbody></table></div>{loading&&<p role="status">Loading orders...</p>}{!loading&&!filtered.length&&<div className="adm-empty"><h3>{orders.length?'No matching orders':'No orders yet'}</h3><p>{orders.length?'Try another order reference.':'Customer orders will appear here.'}</p></div>}<dialog ref={dialog} className="adm-confirm adm-delete-dialog" aria-labelledby="delete-order-title" onCancel={e=>{if(busy)e.preventDefault()}}><span className="adm-delete-emblem"><FiTrash2 /></span><h2 id="delete-order-title">Delete this order?</h2><span className="adm-delete-reference">{pending}</span><p>This permanently removes the recorded order.</p><div className="adm-delete-actions"><button disabled={busy} autoFocus onClick={()=>dialog.current.close()}>Keep order</button><button disabled={busy} className="adm-delete" onClick={async()=>{try{await deleteOrder(pending);dialog.current.close();toast.success('Order deleted.')}catch{toast.error('Unable to delete this order.')}}}>{busy?<><span className="adm-processing-spinner" /> Deleting...</>:'Delete order'}</button></div></dialog></section>
}
