import { useEffect, useRef, useState } from 'react'
import { toast } from 'react-toastify'
import { FiPlus, FiEdit2, FiTrash2, FiStar, FiMessageSquare, FiX } from 'react-icons/fi'
import { useReviews } from '../../store/reviews'
const empty={name:'',title:'',quote:'',label:'',rating:5}
export default function Reviews(){
 const {reviews,saveReview,deleteReview,load,loading,error:loadError,busy}=useReviews()
 useEffect(()=>{load()},[load])
 const [draft,setDraft]=useState(empty),[pending,setPending]=useState(null)
 const editor=useRef(null),confirm=useRef(null)
 const update=(key,value)=>setDraft(current=>({...current,[key]:value}))
 function open(review){setDraft(review?{...review}:{...empty});editor.current.showModal()}
 async function save(event){event.preventDefault();if(busy)return;try{await saveReview(draft);editor.current.close();toast.success(draft.id?'Review updated.':'Review published.')}catch(error){toast.error(error.message)}}
 async function remove(){if(busy)return;try{await deleteReview(pending.id);confirm.current.close();setPending(null);toast.success('Review deleted.')}catch(error){toast.error(error.message||'Unable to delete review.')}}
 return <div className="adm-reviews-page">
 <section className="adm-review-summary" aria-label="Review summary"><span className="adm-review-summary-icon"><FiMessageSquare /></span><div><span>Customer feedback</span><strong>{loading?'...':loadError?'Unavailable':reviews.length}</strong><p>Total reviews</p></div><button disabled={busy} className="adm-primary" onClick={()=>open()}><FiPlus /> Add review</button></section>
 {loading&&<p role="status">Loading reviews...</p>}{loadError&&<p role="alert">{loadError} <button disabled={loading} onClick={load}>Retry</button></p>}
 <section className="adm-panel"><div className="adm-panel-title"><h2>Reviews</h2><span>{reviews.length} {reviews.length===1?'review':'reviews'}</span></div><div className="adm-table-scroll"><table className="adm-reviews-table"><thead><tr><th scope="col">Customer</th><th scope="col">Review</th><th scope="col">Rating</th><th scope="col">Actions</th></tr></thead><tbody>{reviews.map(review=><tr key={review.id}><td><div className="adm-review-customer"><span aria-hidden="true">{review.name.slice(0,1).toUpperCase()}</span><div><strong>{review.name}</strong>{review.label&&<small>{review.label}</small>}</div></div></td><td className="adm-review-copy"><strong>{review.title}</strong><p>{review.quote}</p></td><td><span className="adm-review-rating"><FiStar aria-hidden="true" /> {review.rating} / 5</span></td><td><div className="adm-review-actions"><button className="adm-secondary" aria-label={'Edit review by '+review.name} onClick={()=>open(review)}><FiEdit2 /> Edit</button><button className="adm-secondary" aria-label={'Delete review by '+review.name} onClick={()=>{setPending(review);confirm.current.showModal()}}><FiTrash2 /> Delete</button></div></td></tr>)}</tbody></table></div>{!loading&&!loadError&&!reviews.length&&<div className="adm-empty"><FiMessageSquare /><h3>Your first customer story starts here.</h3><p>Click Add review to publish customer feedback.</p></div>}</section>
 <dialog ref={editor} className="adm-review-editor" aria-labelledby="review-editor-title" onCancel={e=>{if(busy)e.preventDefault()}}><form className="adm-account-card" onSubmit={save}><header><h2 id="review-editor-title">{draft.id?'Edit review':'Post a review'}</h2><button type="button" className="adm-icon" aria-label="Close review form" onClick={()=>editor.current.close()}><FiX /></button></header><p>Publish customer feedback you have permission to share. Published reviews appear on your storefront.</p><fieldset disabled={busy} style={{border:0,padding:0}}><label>Customer display name<input autoFocus required maxLength={80} value={draft.name} onChange={e=>update('name',e.target.value)} /></label><label>Short title<input required maxLength={100} value={draft.title} onChange={e=>update('title',e.target.value)} /></label><label>Customer description (optional)<input maxLength={80} value={draft.label} onChange={e=>update('label',e.target.value)} /></label><label>Rating<select value={draft.rating} onChange={e=>update('rating',e.target.value)}>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} {n===1?'star':'stars'}</option>)}</select></label><label>Review<textarea required maxLength={1000} rows={4} value={draft.quote} onChange={e=>update('quote',e.target.value)} /></label></fieldset><footer><button type="button" className="adm-secondary" onClick={()=>editor.current.close()}>Cancel</button><button type="submit" className="adm-primary">{busy?<><span className="adm-processing-spinner" /> Saving...</>:draft.id?'Save changes':'Post review'}</button></footer></form></dialog>
 <dialog ref={confirm} className="adm-confirm adm-delete-dialog" aria-labelledby="review-delete-title" onCancel={e=>{if(busy)e.preventDefault()}}><span className="adm-delete-emblem"><FiTrash2 /></span><h2 id="review-delete-title">Delete this review?</h2><p>The review by {pending?.name} will be removed from the homepage.</p><div><button autoFocus onClick={()=>confirm.current.close()}>Keep review</button><button className="adm-delete" onClick={remove}>{busy?<><span className="adm-processing-spinner" /> Deleting...</>:'Delete review'}</button></div></dialog>
 </div>
}
