import { useRef, useState } from 'react'
import { toast } from 'react-toastify'
import { useReviews } from '../../store/reviews'
const empty={name:'',title:'',quote:'',label:'',rating:5}
export default function Reviews(){
 const {reviews,saveReview,deleteReview}=useReviews()
 const [draft,setDraft]=useState(empty),[pending,setPending]=useState(null)
 const confirm=useRef(null)
 const update=(key,value)=>setDraft(current=>({...current,[key]:value}))
 return <div className="adm-account-grid"><form className="adm-panel adm-account-card" onSubmit={e=>{e.preventDefault();try{saveReview(draft);setDraft(empty);toast.success('Review published.')}catch(err){toast.error(err.message)}}}><h2>{draft.id?'Edit review':'Post a review'}</h2><p>Publish customer feedback you have permission to share. Reviews currently appear in this browser only.</p><label>Customer display name<input required maxLength={80} value={draft.name} onChange={e=>update('name',e.target.value)} /></label><label>Short title<input required maxLength={100} value={draft.title} onChange={e=>update('title',e.target.value)} /></label><label>Customer description (optional)<input maxLength={80} value={draft.label} onChange={e=>update('label',e.target.value)} /></label><label>Rating<select value={draft.rating} onChange={e=>update('rating',e.target.value)}>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} stars</option>)}</select></label><label>Review<textarea required maxLength={1000} rows={4} value={draft.quote} onChange={e=>update('quote',e.target.value)} /></label><button className="adm-primary">{draft.id?'Save changes':'Post review'}</button>{draft.id&&<button type="button" className="adm-secondary" onClick={()=>setDraft(empty)}>Cancel edit</button>}</form><section className="adm-panel adm-account-card"><h2>Published reviews ({reviews.length})</h2>{!reviews.length&&<p>No customer reviews published yet.</p>}{reviews.map(review=><article key={review.id} className="adm-review-entry"><strong>{review.name} / {review.rating} stars</strong><h3>{review.title}</h3><p>{review.quote}</p><div className="adm-row-actions"><button className="adm-secondary" onClick={()=>setDraft(review)}>Edit</button><button className="adm-secondary" onClick={()=>{setPending(review.id);confirm.current.showModal()}}>Delete</button></div></article>)}</section><dialog ref={confirm} className="adm-confirm adm-delete-dialog"><h2>Delete this review?</h2><p>The review will be removed from the homepage.</p><div><button onClick={()=>confirm.current.close()}>Keep review</button><button className="adm-delete" onClick={()=>{try{deleteReview(pending);if(draft.id===pending)setDraft(empty);confirm.current.close();toast.success('Review deleted.')}catch{toast.error('Unable to delete review.')}}}>Delete</button></div></dialog></div>
}
